### ISSUE TITLE
Touch Focus point reset

### ISSUE THREAD

**Issue by MKaprielian** [Rambalac/GMaster#18]
Hi
Please add if possible the ability to reset the focus point to the center and lock it there.

On the Gx7, G7 and G85 if you move the focus point by touching the screen it give you the option to set it.  You have this part of the functionality now by simply clicking with the mouse anywhere.

On the cameras though, if you press the Disp button it will move the focus point back to the center.   You then have the option to set it there as you would normally have.

I'm suggesting that you have a Disp button that would center and set the focus point.  Granted we can do that with the mouse but it may take several clicks to get what appears to be centered.

   Mark

**Comment by Rambalac** [comment]
I will add reset button to bottom right corner.

**Comment by Rambalac** [comment]
Done in 1.8.5
